/*
 * RMU Tools for Roll20
 * Version 0.4.1
 *
 * Designed for the official "Rolemaster Unified by Iron Crown Enterprises"
 * character sheet.
 *
 * Features:
 *   1) Optional post-Charactermancer fourth stat die.
 *   2) Post-roll stat boosts handled outside Charactermancer
 *      (raise to average / 85 / 90).
 *   3) Post-roll stat swaps handled after all boosts are complete.
 *   4) Pathfinder-like custom buffs managed from chat.
 *
 * IMPORTANT:
 *   Roll20 Mods cannot execute inside the official Charactermancer sandbox.
 *   The stat adjustment is therefore applied AFTER character creation.
 *   In the official Charactermancer, choose "Do Nothing" for the two stat
 *   boosts and for the two stat swaps. Then use this Mod afterwards.
 *
 * v0.4.1:
 *   Adds the campaign house rule granting three EXTRA Raise-to-Average
 *   boosts (Temp 56 / Pot 78 at Superior), separate from the two normal
 *   RMU post-roll boost choices.
 *
 * v0.4.0:
 *   Automatically removes the mandatory Charactermancer stat-boost effects
 *   before the fourth-die house rule is applied. The original Temp/Pot rolls
 *   are reconstructed from the preserved "Temp N, Pot N" creation-history
 *   entry. Supports the official Charactermancer's Raise to Average,
 *   Raise to 85, Raise to 90, and Creation Stat Gain history entries.
 *
 * v0.3.1:
 *   Fixes stat swaps: --swapsecond was accidentally being caught by the
 *   --swaps command parser, resetting the swap workflow to two each time.
 *
 * Commands:
 *   !rmu
 *   !rmu-stats --prepare
 *   !rmu-stats --extra
 *   !rmu-stats --undo-cm-boosts
 *   !rmu-stats --resetworkflow
 *   !rmu-stats --average 2
 *   !rmu-stats --houseaverage 3
 *   !rmu-stats --houseraise agility
 *   !rmu-stats --raise agility
 *   !rmu-stats --raise85
 *   !rmu-stats --raise90
 *   !rmu-stats --swaps 2
 *
 *   !rmu-buff --menu
 *   !rmu-buff --add Bless|+10 to db, +10 to rr
 *   !rmu-buff --toggle <id>
 *   !rmu-buff --on <id>
 *   !rmu-buff --off <id>
 *   !rmu-buff --del <id>
 *   !rmu-buff --refresh
 *
 * All commands operate on the selected token unless --char <character-id>
 * is supplied. Buttons generated by the Mod include --char automatically.
 */

var RMUTools = RMUTools || (function () {
    'use strict';

    const SCRIPT = 'RMUTools';
    const VERSION = '0.4.1';
    const STATE_VERSION = 1;
    const STATE_KEY = 'RMUTools';
    const BUFF_PREFIX = 'RMU Buff [';

    const STAT_INFO = [
        { name: 'agility',        abbr: 'ag', label: 'Agility' },
        { name: 'constitution',   abbr: 'co', label: 'Constitution' },
        { name: 'empathy',        abbr: 'em', label: 'Empathy' },
        { name: 'intuition',      abbr: 'in', label: 'Intuition' },
        { name: 'memory',         abbr: 'me', label: 'Memory' },
        { name: 'presence',       abbr: 'pr', label: 'Presence' },
        { name: 'quickness',      abbr: 'qu', label: 'Quickness' },
        { name: 'reasoning',      abbr: 're', label: 'Reasoning' },
        { name: 'selfdiscipline', abbr: 'sd', label: 'Self Discipline' },
        { name: 'strength',       abbr: 'st', label: 'Strength' }
    ];

    const STAT_ALIASES = (function () {
        const m = {};
        STAT_INFO.forEach(s => {
            m[s.name] = s.abbr;
            m[s.abbr] = s.abbr;
            m[s.label.toLowerCase().replace(/\s+/g, '')] = s.abbr;
        });
        m['self-discipline'] = 'sd';
        m['self discipline'] = 'sd';
        return m;
    }());

    const RR_ATTRS = {
        arcane:     'rr_arcane_misc',
        channeling: 'rr_channeling_misc',
        essence:    'rr_essence_misc',
        mentalism:  'rr_mentalism_misc',
        physical:   'rr_physical_misc',
        fear:       'rr_fear_misc'
    };
    // Mirrors the official RMU sheet's RR definitions.
    const RR_DEFS = {
        arcane:     { stat: 'em/in/pr', label: 'Arcane' },
        channeling: { stat: 'in',       label: 'Channeling' },
        essence:    { stat: 'em',       label: 'Essence' },
        mentalism:  { stat: 'pr',       label: 'Mentalism' },
        physical:   { stat: 'co',       label: 'Physical' },
        fear:       { stat: 'sd',       label: 'Fear' }
    };

    const POWER_LEVELS = {
        average:   { min: 0,  temp: 51, pot: 76 },
        superior:  { min: 11, temp: 56, pot: 78 },
        heroic:    { min: 21, temp: 61, pot: 81 },
        legendary: { min: 31, temp: 66, pot: 83 },
        epic:      { min: 41, temp: 71, pot: 86 }
    };

    function checkInstall() {
        if (!state[STATE_KEY]) {
            state[STATE_KEY] = { version: STATE_VERSION, characters: {} };
        }
        if (!state[STATE_KEY].characters) state[STATE_KEY].characters = {};
        log(`${SCRIPT} v${VERSION} ready`);
    }

    function charState(charId) {
        const root = state[STATE_KEY];
        if (!root.characters[charId]) {
            root.characters[charId] = {
                buffs: {},
                managedAttrs: [],
                pendingAverageRaises: 0,
                pendingHouseAverageRaises: 0,
                houseAverageRaisesRemaining: 0,
                pendingBoosts: 0,
                pendingSwaps: 0,
                pendingSwapFirst: null,
                boostRankOrder: [],
                usedRaise85: false,
                usedRaise90: false
            };
        }
        return root.characters[charId];
    }

    function html(s) {
        return String(s == null ? '' : s)
            .replace(/&/g, '&amp;').replace(/</g, '&lt;')
            .replace(/>/g, '&gt;').replace(/"/g, '&quot;');
    }

    function whisperPlayer(msg, body) {
        const player = getObj('player', msg.playerid);
        const target = player ? player.get('_displayname') : 'gm';
        sendChat(
            SCRIPT,
            `/w "${String(target).replace(/"/g, '')}" ${body}`,
            null,
            { noarchive: true }
        );
    }

    function card(title, body) {
        return `<div style="border:1px solid #777;background:#fff;padding:8px;border-radius:4px;">` +
               `<div style="font-weight:bold;font-size:1.1em;margin-bottom:6px;">${html(title)}</div>` +
               body + `</div>`;
    }

    function button(label, command) { return `[${label}](${command})`; }

    function getAttrObj(charId, name) {
        return findObjs({ _type: 'attribute', _characterid: charId, name: name })[0];
    }

    function getAttr(charId, name, def) {
        const obj = getAttrObj(charId, name);
        if (!obj) return def;
        const v = obj.get('current');
        return (v === undefined || v === null || v === '') ? def : v;
    }

    function setAttr(charId, name, value, worker) {
        let obj = getAttrObj(charId, name);
        if (!obj) {
            obj = createObj('attribute', { characterid: charId, name: name, current: value });
            if (worker && obj && obj.setWithWorker) obj.setWithWorker({ current: value });
            return obj;
        }
        if (worker && obj.setWithWorker) obj.setWithWorker({ current: value });
        else obj.set('current', value);
        return obj;
    }

    function selectedCharacter(msg, explicitId) {
        if (explicitId) {
            const c = getObj('character', explicitId);
            if (c) return c;
        }
        if (msg.selected && msg.selected.length) {
            for (let i = 0; i < msg.selected.length; i++) {
                const token = getObj('graphic', msg.selected[i]._id);
                if (!token) continue;
                const charId = token.get('represents');
                if (!charId) continue;
                const c = getObj('character', charId);
                if (c) return c;
            }
        }
        return null;
    }

    function extractCharArg(content) {
        const m = content.match(/\s--char\s+([A-Za-z0-9_-]+)/);
        if (!m) return { charId: null, content: content };
        return { charId: m[1], content: content.replace(m[0], '') };
    }

    function safeMiscParse(value) {
        if (!value) return [];
        try {
            const parsed = JSON.parse(value);
            return Array.isArray(parsed) ? parsed : [];
        } catch (e) { return []; }
    }

    function miscSetNamedValue(value, name, number) {
        const arr = safeMiscParse(value);
        let found = false;
        arr.forEach(o => {
            if (o && o.name === name) {
                delete o.absolute;
                o.value = parseInt(number, 10) || 0;
                found = true;
            }
        });
        if (!found) arr.push({ name: name, value: parseInt(number, 10) || 0 });
        return JSON.stringify(arr);
    }

    function miscSetAbsolute(value, name, number) {
        const arr = safeMiscParse(value);
        let found = false;
        arr.forEach(o => {
            if (o && o.name === name) {
                delete o.value;
                o.absolute = parseInt(number, 10) || 0;
                found = true;
            }
        });
        if (!found) arr.push({ name: name, absolute: parseInt(number, 10) || 0 });
        return JSON.stringify(arr);
    }

    function miscTotal(value) {
        const arr = safeMiscParse(value);
        let total = 0;
        arr.forEach(o => {
            if (!o) return;
            if (Object.prototype.hasOwnProperty.call(o, 'absolute')) total = parseInt(o.absolute, 10) || 0;
            else if (Object.prototype.hasOwnProperty.call(o, 'value')) total += parseInt(o.value, 10) || 0;
        });
        return total;
    }

    function isOwnRealmForRR(rrName, characterRealm) {
        const realm = String(characterRealm || '')
            .toLowerCase()
            .replace(/[^a-z]/g, '');

        if (!realm) return false;
        if (rrName === 'arcane') return realm === 'arcane';

        // Handles both single realms and hybrid names such as
        // "Channeling/Essence".
        return realm.indexOf(rrName) !== -1;
    }

    function recalcResistanceRolls(charId) {
        const level = parseInt(getAttr(charId, 'level', 0), 10) || 0;
        const characterRealm = getAttr(charId, 'realm', '');
        const updates = {};

        Object.keys(RR_DEFS).forEach(rrName => {
            const def = RR_DEFS[rrName];
            const stats = def.stat.split('/');

            // Mirrors the official RMU sheet: for multi-stat RRs, use the
            // best current realm-stat bonus.
            let statBonus = -1000;
            const statLines = [];
            stats.forEach(stat => {
                const value = parseInt(getAttr(charId, stat, 0), 10) || 0;
                if (value > statBonus) statBonus = value;
                statLines.push(`${value} ${stat.toUpperCase()} Bonus`);
            });
            if (statBonus === -1000) statBonus = 0;

            const miscAttr = RR_ATTRS[rrName];
            const misc = miscTotal(getAttr(charId, miscAttr, '[]'));
            const ownRealm = isOwnRealmForRR(rrName, characterRealm) ? 10 : 0;
            const bonus = statBonus + misc + (level * 2) + ownRealm;

            updates[`rr_${rrName}_bonus`] = bonus;
            updates[`rr_${rrName}_info`] =
                `${statBonus} Realm Stat Bonus\n` +
                `${misc} Miscellaneous\n` +
                `${level * 2} Twice Level\n` +
                `${ownRealm} Own Realm\n` +
                statLines.join('\n');
        });

        Object.keys(updates).forEach(attr => {
            setAttr(charId, attr, updates[attr], false);
        });
    }

    function cleanTargetText(s) {
        return String(s || '').trim().toLowerCase().replace(/\s+/g, ' ');
    }

    function resolveEffectTargets(charId, targetText) {
        let t = cleanTargetText(targetText).replace(/^to\s+/, '');
        if (t === 'db' || t === 'defensive bonus' || t === 'defence' || t === 'defense') return ['db_misc'];
        if (t === 'rr' || t === 'rrs' || t === 'resistance' || t === 'resistance roll' || t === 'resistance rolls') {
            return Object.keys(RR_ATTRS).map(k => RR_ATTRS[k]);
        }

        let rr = t.match(/^(?:rr\s+|resistance(?:\s+roll)?\s+)(arcane|channeling|essence|mentalism|physical|fear)$/);
        if (!rr) rr = t.match(/^(arcane|channeling|essence|mentalism|physical|fear)\s+(?:rr|resistance(?:\s+roll)?)$/);
        if (rr) return [RR_ATTRS[rr[1]]];

        const statKey = t.replace(/\s+/g, '');
        if (STAT_ALIASES[t] || STAT_ALIASES[statKey]) return [(STAT_ALIASES[t] || STAT_ALIASES[statKey]) + '_misc'];

        if (t.indexOf('attr:') === 0) {
            let a = t.substring(5).trim();
            if (a && !/_misc$/.test(a)) a += '_misc';
            return a ? [a] : [];
        }

        const candidate = t.replace(/[^a-z0-9]/g, '') + '_misc';
        if (getAttrObj(charId, candidate)) return [candidate];
        return [];
    }

    function parseEffects(charId, effectText) {
        const clauses = String(effectText || '').split(/[,;\n]+/).map(s => s.trim()).filter(Boolean);
        const effects = [], errors = [];
        clauses.forEach(clause => {
            const m = clause.match(/^([+-]?\d+)\s+(?:to\s+)?(.+)$/i);
            if (!m) { errors.push(`Could not parse "${clause}"`); return; }
            const value = parseInt(m[1], 10);
            const targetText = m[2].trim();
            const attrs = resolveEffectTargets(charId, targetText);
            if (!attrs.length) { errors.push(`Unknown target "${targetText}"`); return; }
            effects.push({ value: value, target: targetText, attrs: attrs });
        });
        return { effects: effects, errors: errors };
    }

    function buffTag(buff) { return `${BUFF_PREFIX}${buff.id}] ${buff.name}`; }

    function reconcileBuffs(charId) {
        const cs = charState(charId), activeByAttr = {};
        Object.keys(cs.buffs).forEach(id => {
            const buff = cs.buffs[id];
            if (!buff.active) return;
            buff.effects.forEach(e => e.attrs.forEach(attr => {
                if (!activeByAttr[attr]) activeByAttr[attr] = [];
                activeByAttr[attr].push({ name: buffTag(buff), value: e.value });
                if (cs.managedAttrs.indexOf(attr) === -1) cs.managedAttrs.push(attr);
            }));
        });

        cs.managedAttrs.forEach(attr => {
            let arr = safeMiscParse(getAttr(charId, attr, '[]'));
            arr = arr.filter(o => !(o && typeof o.name === 'string' && o.name.indexOf(BUFF_PREFIX) === 0));
            (activeByAttr[attr] || []).forEach(e => arr.push({ name: e.name, value: e.value }));
            setAttr(charId, attr, JSON.stringify(arr), true);
        });

        // The official RMU sheet does not watch rr_*_misc for changes.
        // Recalculate the displayed/rolled RR bonuses ourselves whenever
        // this Mod manages any RR misc attribute.
        if (cs.managedAttrs.some(attr =>
            /^rr_(arcane|channeling|essence|mentalism|physical|fear)_misc$/.test(attr))) {
            recalcResistanceRolls(charId);
        }
    }

    function buffMenu(msg, character) {
        const charId = character.id, cs = charState(charId);
        const buffs = Object.keys(cs.buffs).map(id => cs.buffs[id]);
        let body = `<div><b>${html(character.get('name'))}</b></div>`;
        body += `<div style="margin:5px 0;">` +
                button('Add buff', `!rmu-buff --char ${charId} --add ?{Buff name}|?{Effects|+10 to db, +10 to rr}`) +
                ` ${button('Refresh', `!rmu-buff --char ${charId} --refresh`)}</div>`;
        if (!buffs.length) body += `<div><i>No custom buffs defined.</i></div>`;
        else buffs.forEach(buff => {
            const status = buff.active ? 'ON' : 'off';
            const effects = buff.effects.map(e => `${e.value >= 0 ? '+' : ''}${e.value} to ${e.target}`).join(', ');
            body += `<div style="border-top:1px solid #ddd;padding-top:4px;margin-top:4px;">` +
                    `<b>${html(buff.name)}</b> [${status}]<br><span style="font-size:90%">${html(effects)}</span><br>` +
                    `${button(buff.active ? 'Disable' : 'Enable', `!rmu-buff --char ${charId} --toggle ${buff.id}`)} ` +
                    `${button('Delete', `!rmu-buff --char ${charId} --del ${buff.id}`)}</div>`;
        });
        body += `<div style="margin-top:6px;font-size:90%">Effect syntax: <code>+10 to db</code>, ` +
                `<code>+10 to rr</code>, <code>+20 to fear rr</code>, or ` +
                `<code>+10 to attr:perception_misc</code>.</div>`;
        whisperPlayer(msg, card('RMU Buffs', body));
    }

    function handleBuff(msg, raw) {
        const ext = extractCharArg(raw), character = selectedCharacter(msg, ext.charId);
        if (!character) { whisperPlayer(msg, card('RMU Buffs', 'Select a token representing a character, then try again.')); return; }
        const charId = character.id, cs = charState(charId), content = ext.content;
        let m;

        if ((m = content.match(/\s--add\s+([\s\S]+)$/))) {
            const spec = m[1], split = spec.indexOf('|');
            if (split < 1) { whisperPlayer(msg, card('RMU Buffs', 'Use <code>--add Name|+10 to db, +10 to rr</code>.')); return; }
            const name = spec.substring(0, split).trim(), effectText = spec.substring(split + 1).trim();
            const parsed = parseEffects(charId, effectText);
            if (!name || !parsed.effects.length || parsed.errors.length) {
                let body = !name ? 'Buff name is missing.<br>' : '';
                parsed.errors.forEach(e => body += `${html(e)}<br>`);
                whisperPlayer(msg, card('RMU Buffs', body || 'No valid effects.')); return;
            }
            const id = Date.now().toString(36) + randomInteger(9999).toString(36);
            cs.buffs[id] = { id: id, name: name, effectText: effectText, effects: parsed.effects, active: true };
            reconcileBuffs(charId); buffMenu(msg, character); return;
        }

        const actionMatch = content.match(/\s--(toggle|on|off|del)\s+([A-Za-z0-9_-]+)/);
        if (actionMatch) {
            const action = actionMatch[1], id = actionMatch[2], buff = cs.buffs[id];
            if (!buff) { whisperPlayer(msg, card('RMU Buffs', 'Buff not found.')); return; }
            if (action === 'toggle') buff.active = !buff.active;
            if (action === 'on') buff.active = true;
            if (action === 'off') buff.active = false;
            if (action === 'del') delete cs.buffs[id];
            reconcileBuffs(charId); buffMenu(msg, character); return;
        }

        if (/\s--refresh\b/.test(content)) { reconcileBuffs(charId); buffMenu(msg, character); return; }
        buffMenu(msg, character);
    }

    function powerLevelInfo(charId) {
        const raw = String(getAttr(charId, 'powerlevel', 'Superior')).trim().toLowerCase();
        return POWER_LEVELS[raw] || POWER_LEVELS.superior;
    }

    function rerollD100Below(minimum) {
        let r;
        do { r = randomInteger(100); } while (minimum > 0 && r < minimum);
        return r;
    }

    function originalCreationRolls(charId, statName) {
        const arr = safeMiscParse(getAttr(charId, statName + '_misc', ''));
        for (let i = 0; i < arr.length; i++) {
            const o = arr[i];
            if (!o || typeof o.name !== 'string') continue;
            const m = o.name.match(/^Temp\s+(\d+),\s*Pot\s+(\d+)/i);
            if (m) return { temp: parseInt(m[1], 10), pot: parseInt(m[2], 10), index: i, array: arr };
        }
        return null;
    }

    function isCharactermancerStatBoostEntry(entry) {
        if (!entry || typeof entry.name !== 'string') return false;
        return /^Raise to average \(Pot \d+\)$/i.test(entry.name) ||
               /^Raise highest to (?:85|90) \(Pot \d+\)$/i.test(entry.name) ||
               /^Creation stat gain - \d+ [AB]$/i.test(entry.name);
    }

    function undoCharactermancerStatBoosts(msg, character, quiet) {
        const charId = character.id;
        const results = [];
        let changedStats = 0;
        let removedEntries = 0;

        STAT_INFO.forEach(stat => {
            const tempAttr = stat.name + '_misc';
            const potAttr = stat.name + '_pot_misc';
            const arr = safeMiscParse(getAttr(charId, tempAttr, '[]'));

            // createStatsFinalize() always writes the untouched rolled pair
            // first as "Temp N, Pot N". Later mandatory Charactermancer boost
            // choices append their own history entries. Even when Potential
            // is subsequently overwritten, the original Pot survives here.
            let original = null;
            for (let i = 0; i < arr.length; i++) {
                const o = arr[i];
                if (!o || typeof o.name !== 'string') continue;
                const m = o.name.match(/^Temp\s+(\d+),\s*Pot\s+(\d+)/i);
                if (m) {
                    original = {
                        temp: parseInt(m[1], 10),
                        pot: parseInt(m[2], 10)
                    };
                    break;
                }
            }

            if (!original) {
                results.push(`${stat.label}: original Temp/Pot history not found`);
                return;
            }

            const beforeCount = arr.length;
            const cleaned = arr.filter(o => !isCharactermancerStatBoostEntry(o));
            const removed = beforeCount - cleaned.length;

            // Restore the Potential Creation entry even if the only CM boost
            // affected Potential and no Temp-history entry remains after a
            // previous manual cleanup.
            const oldPot = miscTotal(getAttr(charId, potAttr, '[]'));
            const oldTemp = miscTotal(getAttr(charId, tempAttr, '[]'));

            if (removed > 0 || oldPot !== original.pot) {
                setAttr(charId, tempAttr, JSON.stringify(cleaned), true);
                setAttr(
                    charId,
                    potAttr,
                    miscSetNamedValue(getAttr(charId, potAttr, '[]'), 'Creation', original.pot),
                    true
                );
                changedStats += 1;
                removedEntries += removed;
                results.push(`${stat.label}: restored creation ${original.temp}/${original.pot}` +
                             `${removed ? `; removed ${removed} CM boost entr${removed === 1 ? 'y' : 'ies'}` : ''}`);
            }
        });

        const cs = charState(charId);
        cs.lastCMUndo = {
            when: Date.now(),
            changedStats: changedStats,
            removedEntries: removedEntries
        };

        if (!quiet) {
            const body = `<div><b>${html(character.get('name'))}</b></div>` +
                `<div style="margin-top:5px">Restored <b>${changedStats}</b> stat(s) to their original ` +
                `Charactermancer creation rolls and removed <b>${removedEntries}</b> mandatory boost-history entr${removedEntries === 1 ? 'y' : 'ies'}.</div>` +
                `<div style="margin-top:5px;font-size:90%">Recognized Charactermancer entries: Raise to Average, Raise to 85, Raise to 90, and Creation Stat Gain.</div>` +
                (results.length ? `<div style="margin-top:5px">${results.join('<br>')}</div>` : '');
            whisperPlayer(msg, card('RMU undo Charactermancer boosts', body));
        }

        return {
            changedStats: changedStats,
            removedEntries: removedEntries,
            results: results
        };
    }

    function applyExtraStatDie(msg, character) {
        const charId = character.id, pli = powerLevelInfo(charId), results = [], updates = [];
        const undo = undoCharactermancerStatBoosts(msg, character, true);
        STAT_INFO.forEach(stat => {
            const original = originalCreationRolls(charId, stat.name);
            if (!original) { results.push(`${stat.label}: could not find original creation roll`); return; }
            const extra = rerollD100Below(pli.min);
            const sorted = [original.pot, original.temp, extra].sort((a, b) => b - a);
            const newPot = sorted[0], newTemp = sorted[1];

            const entry = original.array[original.index];
            entry.name = `Temp ${newTemp}, Pot ${newPot} (4th die ${extra})`;
            entry.absolute = newTemp;
            delete entry.value;
            setAttr(charId, stat.name + '_misc', JSON.stringify(original.array), true);

            const potAttr = stat.name + '_pot_misc';
            const currentPot = miscTotal(getAttr(charId, potAttr, '[]'));
            if (newPot > currentPot) {
                setAttr(charId, potAttr, miscSetNamedValue(getAttr(charId, potAttr, '[]'), 'Creation', newPot), true);
            }

            const changed = (newPot !== original.pot || newTemp !== original.temp);
            results.push(`${stat.label}: rolled <b>${extra}</b> &rarr; ${original.pot}/${original.temp} becomes ` +
                         `<b>${newPot}/${newTemp}</b>${changed ? '' : ' (no change)'}`);
            updates.push({ stat: stat.name, die: extra, changed: changed });
        });

        const cs = initializePostRollWorkflow(charId);
        cs.lastExtraDie = { when: Date.now(), powerMin: pli.min, results: updates };

        whisperPlayer(msg, card('RMU fourth stat die',
            `<div><b>${html(character.get('name'))}</b></div>` +
            `<div style="margin-top:5px"><b>Before rolling:</b> restored ${undo.changedStats} stat(s) and removed ${undo.removedEntries} Charactermancer boost-history entr${undo.removedEntries === 1 ? 'y' : 'ies'}.</div>` +
            `<div style="margin-top:5px">${results.join('<br>')}</div>` +
            `<div style="margin-top:6px;font-size:90%"><b>Workflow reset:</b> ` +
            `you now have <b>${cs.pendingBoosts}</b> normal post-roll boost choices, ` +
            `<b>${cs.houseAverageRaisesRemaining}</b> extra house-rule Raise-to-Average boosts, and ` +
            `<b>${cs.pendingSwaps}</b> post-roll stat swaps remaining. ` +
            `Complete all boosts first, then do your swaps at the end.</div>`));
    }

    function currentStatValue(charId, statName) { return miscTotal(getAttr(charId, statName + '_misc', '[]')); }
    function currentPotValue(charId, statName) { return miscTotal(getAttr(charId, statName + '_pot_misc', '[]')); }

    function rankStatNamesByCreationTemp(charId) {
        const indexMap = {};
        STAT_INFO.forEach((s, idx) => { indexMap[s.name] = idx; });

        return STAT_INFO.map(stat => {
            const r = originalCreationRolls(charId, stat.name);
            return {
                name: stat.name,
                temp: r ? r.temp : -999,
                pot: r ? r.pot : -999
            };
        }).sort((a, b) => {
            if (b.temp !== a.temp) return b.temp - a.temp;
            if (b.pot !== a.pot) return b.pot - a.pot;
            return indexMap[a.name] - indexMap[b.name];
        }).map(r => r.name);
    }

    function initializePostRollWorkflow(charId) {
        const cs = charState(charId);
        cs.pendingBoosts = 2;
        cs.pendingAverageRaises = 0;
        cs.houseAverageRaisesRemaining = 3;
        cs.pendingHouseAverageRaises = 0;
        cs.pendingSwaps = 2;
        cs.pendingSwapFirst = null;
        cs.usedRaise85 = false;
        cs.usedRaise90 = false;
        cs.boostRankOrder = rankStatNamesByCreationTemp(charId);
        return cs;
    }

    function ensureBoostRankOrder(charId) {
        const cs = charState(charId);
        if (!Array.isArray(cs.boostRankOrder) || !cs.boostRankOrder.length) {
            cs.boostRankOrder = rankStatNamesByCreationTemp(charId);
        }
        return cs.boostRankOrder;
    }

    function fixedRaiseTargetName(charId, target) {
        const order = ensureBoostRankOrder(charId);
        if (target === 90) return order[0] || null;
        if (target === 85) return order[1] || null;
        return null;
    }

    function requireBoostAvailable(msg, character) {
        const cs = charState(character.id);
        if ((cs.pendingBoosts || 0) < 1) {
            whisperPlayer(msg, card('RMU Stats',
                `No post-roll boost choices remain for <b>${html(character.get('name'))}</b>. ` +
                `Use <code>!rmu-stats --resetworkflow</code> if you need to reinitialize the ` +
                `post-roll workflow from the current creation stats.`));
            return false;
        }
        return true;
    }


    function findStat(statName) {
        const key = String(statName || '').toLowerCase();
        return STAT_INFO.find(s => s.name === key || s.abbr === key) || null;
    }

    function setCreationPackage(charId, statName, temp, pot, note) {
        const creation = originalCreationRolls(charId, statName);
        if (!creation) return false;

        const entry = creation.array[creation.index];
        entry.name = `Temp ${temp}, Pot ${pot}${note ? ' (' + note + ')' : ''}`;
        entry.absolute = temp;
        delete entry.value;
        setAttr(charId, statName + '_misc', JSON.stringify(creation.array), true);

        const potAttr = statName + '_pot_misc';
        setAttr(charId, potAttr,
            miscSetNamedValue(getAttr(charId, potAttr, '[]'), 'Creation', pot), true);
        return true;
    }

    function swapCreationStats(msg, character, statAName, statBName) {
        const charId = character.id;
        const a = findStat(statAName), b = findStat(statBName);
        if (!a || !b || a.name === b.name) {
            whisperPlayer(msg, card('RMU Stat Swap', 'Choose two different valid stats.'));
            return false;
        }

        const av = originalCreationRolls(charId, a.name);
        const bv = originalCreationRolls(charId, b.name);
        if (!av || !bv) {
            whisperPlayer(msg, card('RMU Stat Swap', 'Could not locate the original creation values for both stats.'));
            return false;
        }

        // Swap only the creation Temp/Potential package. Racial bonuses,
        // buffs, and other later misc entries stay attached to their stats.
        setCreationPackage(charId, a.name, bv.temp, bv.pot, `swapped from ${b.label}`);
        setCreationPackage(charId, b.name, av.temp, av.pot, `swapped from ${a.label}`);

        whisperPlayer(msg, card('RMU Stat Swap',
            `<b>${html(a.label)}</b> ${av.temp}/${av.pot} &harr; ` +
            `<b>${html(b.label)}</b> ${bv.temp}/${bv.pot}`));
        return true;
    }

    function swapMenu(msg, character) {
        const charId = character.id, cs = charState(charId);
        const remaining = cs.pendingSwaps || 0;
        let body = `<div><b>${html(character.get('name'))}</b></div>` +
                   `<div>Swaps remaining: <b>${remaining}</b></div>`;

        if (remaining < 1) {
            body += `<div style="margin-top:5px"><i>No stat swaps pending.</i></div>`;
            whisperPlayer(msg, card('RMU Stat Swaps', body));
            return;
        }

        if (!cs.pendingSwapFirst) {
            body += `<div style="margin-top:5px">Choose the first stat:</div>`;
            STAT_INFO.forEach(stat => {
                const r = originalCreationRolls(charId, stat.name);
                const values = r ? `${r.temp}/${r.pot}` : '?/?';
                body += `<div>${button(stat.label, `!rmu-stats --char ${charId} --swapfirst ${stat.name}`)} ${values}</div>`;
            });
        } else {
            const first = findStat(cs.pendingSwapFirst);
            body += `<div style="margin-top:5px">Swap <b>${html(first ? first.label : cs.pendingSwapFirst)}</b> with:</div>`;
            STAT_INFO.filter(stat => stat.name !== cs.pendingSwapFirst).forEach(stat => {
                const r = originalCreationRolls(charId, stat.name);
                const values = r ? `${r.temp}/${r.pot}` : '?/?';
                body += `<div>${button(stat.label, `!rmu-stats --char ${charId} --swapsecond ${stat.name}`)} ${values}</div>`;
            });
            body += `<div style="margin-top:4px">${button('Cancel selection', `!rmu-stats --char ${charId} --swapcancel`)}</div>`;
        }
        whisperPlayer(msg, card('RMU Stat Swaps', body));
    }

    function applyFixedRaise(msg, character, target) {
        const charId = character.id;
        const cs = charState(charId);

        if (!requireBoostAvailable(msg, character)) return;

        if (target === 90 && cs.usedRaise90) {
            whisperPlayer(msg, card('RMU Raise to 90',
                'The post-roll <b>Raise to 90</b> option has already been used in this workflow.'));
            return;
        }
        if (target === 85 && cs.usedRaise85) {
            whisperPlayer(msg, card('RMU Raise to 85',
                'The post-roll <b>Raise to 85</b> option has already been used in this workflow.'));
            return;
        }

        const statName = fixedRaiseTargetName(charId, target);
        const stat = findStat(statName);
        if (!stat) {
            whisperPlayer(msg, card(`RMU Raise to ${target}`,
                'Could not determine the correct stat for this post-roll boost.'));
            return;
        }

        const r = originalCreationRolls(charId, stat.name);
        if (!r) {
            whisperPlayer(msg, card(`RMU Raise to ${target}`,
                'Could not locate the original creation values for that stat.'));
            return;
        }

        const newTemp = Math.max(r.temp, target);
        const newPot = Math.min(100, Math.max(r.pot + 10, newTemp));
        setCreationPackage(charId, stat.name, newTemp, newPot, `raised to ${target}`);

        cs.pendingBoosts = Math.max(0, (cs.pendingBoosts || 0) - 1);
        if (target === 90) cs.usedRaise90 = true;
        if (target === 85) cs.usedRaise85 = true;

        whisperPlayer(msg, card(`RMU Raise to ${target}`,
            `<b>${html(stat.label)}</b> was the locked post-roll target for Raise to ${target}.<br>` +
            `It changed from ${r.temp}/${r.pot} to <b>${newTemp}/${newPot}</b>.<br>` +
            `Post-roll boosts remaining: <b>${cs.pendingBoosts}</b>.`));
    }

    function averageRaiseMenu(msg, character) {
        const charId = character.id, cs = charState(charId), pli = powerLevelInfo(charId);
        const remaining = cs.pendingAverageRaises || 0;
        let body = `<div><b>${html(character.get('name'))}</b></div>` +
                   `<div>Average raises waiting to be assigned: <b>${remaining}</b></div>` +
                   `<div>Total post-roll boosts remaining: <b>${cs.pendingBoosts || 0}</b></div>` +
                   `<div>Average: Temp ${pli.temp}, Pot ${pli.pot}</div>`;
        if (remaining > 0) {
            body += `<div style="margin-top:5px">Choose a stat:</div>`;
            STAT_INFO.forEach(stat => {
                const temp = currentStatValue(charId, stat.name), pot = currentPotValue(charId, stat.name);
                body += `<div>${button(stat.label, `!rmu-stats --char ${charId} --raise ${stat.name}`)} ${temp}/${pot}</div>`;
            });
        } else body += `<div style="margin-top:5px"><i>No average raises pending.</i></div>`;
        whisperPlayer(msg, card('RMU raise to average', body));
    }

    function applyAverageRaise(msg, character, statName) {
        const charId = character.id, cs = charState(charId);
        if ((cs.pendingAverageRaises || 0) < 1) {
            whisperPlayer(msg, card('RMU Stats', 'No average raises are pending. Use <code>!rmu-stats --average 1</code> or <code>--average 2</code> first.'));
            return;
        }
        if (!requireBoostAvailable(msg, character)) return;

        const stat = STAT_INFO.filter(s => s.name === statName.toLowerCase())[0];
        if (!stat) { whisperPlayer(msg, card('RMU Stats', `Unknown stat "${html(statName)}".`)); return; }

        const pli = powerLevelInfo(charId), tempAttr = stat.name + '_misc', potAttr = stat.name + '_pot_misc';
        const oldTemp = currentStatValue(charId, stat.name), oldPot = currentPotValue(charId, stat.name);
        const newTemp = Math.max(oldTemp, pli.temp), newPot = Math.max(oldPot, pli.pot);

        setAttr(charId, tempAttr, miscSetAbsolute(getAttr(charId, tempAttr, '[]'), 'RMU Mod: Raise to average', newTemp), true);
        setAttr(charId, potAttr, miscSetAbsolute(getAttr(charId, potAttr, '[]'), 'RMU Mod: Raise to average', newPot), true);

        cs.pendingAverageRaises = Math.max(0, (cs.pendingAverageRaises || 0) - 1);
        cs.pendingBoosts = Math.max(0, (cs.pendingBoosts || 0) - 1);

        whisperPlayer(msg, card('RMU Stats', `${html(stat.label)} raised from ${oldTemp}/${oldPot} to ` +
            `<b>${newTemp}/${newPot}</b>. Average raises waiting: <b>${cs.pendingAverageRaises}</b>. ` +
            `Post-roll boosts remaining: <b>${cs.pendingBoosts}</b>.`));
        if (cs.pendingAverageRaises > 0) averageRaiseMenu(msg, character);
    }

    function houseAverageRaiseMenu(msg, character) {
        const charId = character.id, cs = charState(charId), pli = powerLevelInfo(charId);
        const pending = cs.pendingHouseAverageRaises || 0;
        let body = `<div><b>${html(character.get('name'))}</b></div>` +
                   `<div>House-rule average raises waiting to be assigned: <b>${pending}</b></div>` +
                   `<div>Total house-rule average raises remaining: <b>${cs.houseAverageRaisesRemaining || 0}</b></div>` +
                   `<div>Average: Temp ${pli.temp}, Pot ${pli.pot}</div>`;
        if (pending > 0) {
            body += `<div style="margin-top:5px">Choose a stat:</div>`;
            STAT_INFO.forEach(stat => {
                const temp = currentStatValue(charId, stat.name), pot = currentPotValue(charId, stat.name);
                body += `<div>${button(stat.label, `!rmu-stats --char ${charId} --houseraise ${stat.name}`)} ${temp}/${pot}</div>`;
            });
        } else {
            body += `<div style="margin-top:5px"><i>No house-rule average raises are pending.</i></div>`;
        }
        whisperPlayer(msg, card('RMU house-rule Raise to Average', body));
    }

    function applyHouseAverageRaise(msg, character, statName) {
        const charId = character.id, cs = charState(charId);
        if ((cs.pendingHouseAverageRaises || 0) < 1 || (cs.houseAverageRaisesRemaining || 0) < 1) {
            whisperPlayer(msg, card('RMU Stats',
                'No house-rule Raise-to-Average boosts are pending. Use <code>!rmu-stats --houseaverage 3</code> first.'));
            return;
        }

        const stat = STAT_INFO.filter(s => s.name === statName.toLowerCase())[0];
        if (!stat) {
            whisperPlayer(msg, card('RMU Stats', `Unknown stat "${html(statName)}".`));
            return;
        }

        const pli = powerLevelInfo(charId);
        const tempAttr = stat.name + '_misc', potAttr = stat.name + '_pot_misc';
        const oldTemp = currentStatValue(charId, stat.name), oldPot = currentPotValue(charId, stat.name);
        const newTemp = Math.max(oldTemp, pli.temp), newPot = Math.max(oldPot, pli.pot);

        setAttr(
            charId,
            tempAttr,
            miscSetAbsolute(getAttr(charId, tempAttr, '[]'), 'RMU Mod: House Raise to average', newTemp),
            true
        );
        setAttr(
            charId,
            potAttr,
            miscSetAbsolute(getAttr(charId, potAttr, '[]'), 'RMU Mod: House Raise to average', newPot),
            true
        );

        cs.pendingHouseAverageRaises = Math.max(0, (cs.pendingHouseAverageRaises || 0) - 1);
        cs.houseAverageRaisesRemaining = Math.max(0, (cs.houseAverageRaisesRemaining || 0) - 1);

        whisperPlayer(msg, card('RMU house-rule Raise to Average',
            `${html(stat.label)} raised from ${oldTemp}/${oldPot} to <b>${newTemp}/${newPot}</b>.<br>` +
            `House-rule average raises remaining: <b>${cs.houseAverageRaisesRemaining}</b>.`));

        if (cs.pendingHouseAverageRaises > 0) houseAverageRaiseMenu(msg, character);
    }

    function handleStats(msg, raw) {
        const ext = extractCharArg(raw), character = selectedCharacter(msg, ext.charId);
        if (!character) { whisperPlayer(msg, card('RMU Stats', 'Select a token representing a character, then try again.')); return; }
        const charId = character.id, content = ext.content, cs = charState(charId);
        let m;

        if (/\s--undo-cm-boosts\b/.test(content)) {
            undoCharactermancerStatBoosts(msg, character, false);
            return;
        }

        if (/\s--prepare\b/.test(content)) {
            const undo = undoCharactermancerStatBoosts(msg, character, true);
            initializePostRollWorkflow(charId);
            whisperPlayer(msg, card('RMU Stat Preparation',
                `<div><b>${html(character.get('name'))}</b></div>` +
                `<div>Removed <b>${undo.removedEntries}</b> Charactermancer mandatory boost-history entr${undo.removedEntries === 1 ? 'y' : 'ies'} and restored the original creation Potential values.</div>` +
                `<div style="margin-top:5px">The character is now ready for the fourth die.</div>` +
                `<div style="margin-top:5px">${button('Roll fourth die', `!rmu-stats --char ${charId} --extra`)}</div>`));
            return;
        }

        if (/\s--extra\b/.test(content)) { applyExtraStatDie(msg, character); return; }

        if (/\s--resetworkflow\b/.test(content)) {
            initializePostRollWorkflow(charId);
            whisperPlayer(msg, card('RMU Stat Workflow',
                `<div><b>${html(character.get('name'))}</b></div>` +
                `<div>Post-roll workflow reset from the current creation stats.</div>` +
                `<div>You now have <b>2</b> normal boost choices, <b>3</b> extra house-rule Raise-to-Average boosts, and <b>2</b> stat swaps remaining.</div>` +
                `<div style="margin-top:5px;font-size:90%">This button resets only RMU Tools counters and the locked 85/90 ranking. It does not undo stat values. Normally use the fourth-die button, which automatically removes mandatory Charactermancer boost effects first.</div>`));
            return;
        }

        if ((m = content.match(/\s--average(?:\s+(\d+))?/))) {
            if (!requireBoostAvailable(msg, character)) return;
            const requested = Math.max(1, Math.min(10, parseInt(m[1] || '1', 10)));
            const allowed = Math.min(requested, cs.pendingBoosts || 0);
            if (allowed < 1) {
                whisperPlayer(msg, card('RMU Stats', 'No post-roll boosts remain.'));
                return;
            }
            cs.pendingAverageRaises = allowed;
            averageRaiseMenu(msg, character); return;
        }
        if ((m = content.match(/\s--raise\s+([A-Za-z-]+)/))) { applyAverageRaise(msg, character, m[1]); return; }

        if ((m = content.match(/\s--houseaverage(?:\s+(\d+))?/))) {
            const available = cs.houseAverageRaisesRemaining || 0;
            if (available < 1) {
                whisperPlayer(msg, card('RMU Stats', 'No extra house-rule Raise-to-Average boosts remain.'));
                return;
            }
            const requested = Math.max(1, Math.min(3, parseInt(m[1] || String(available), 10)));
            cs.pendingHouseAverageRaises = Math.min(requested, available);
            houseAverageRaiseMenu(msg, character);
            return;
        }
        if ((m = content.match(/\s--houseraise\s+([A-Za-z-]+)/))) {
            applyHouseAverageRaise(msg, character, m[1]);
            return;
        }

        if (/\s--raise90\b/.test(content)) { applyFixedRaise(msg, character, 90); return; }
        if (/\s--raise85\b/.test(content)) { applyFixedRaise(msg, character, 85); return; }

        if ((m = content.match(/\s--swaps\b(?:\s+(\d+))?/))) {
            if ((cs.pendingBoosts || 0) > 0 || (cs.pendingAverageRaises || 0) > 0 ||
                (cs.houseAverageRaisesRemaining || 0) > 0 || (cs.pendingHouseAverageRaises || 0) > 0) {
                whisperPlayer(msg, card('RMU Stat Swaps',
                    `Finish all post-roll boosts first. Normal boosts remaining: <b>${cs.pendingBoosts || 0}</b>; ` +
                    `house-rule average boosts remaining: <b>${cs.houseAverageRaisesRemaining || 0}</b>.`));
                return;
            }
            cs.pendingSwaps = Math.max(1, Math.min(10, parseInt(m[1] || String(cs.pendingSwaps || 2), 10)));
            cs.pendingSwapFirst = null;
            swapMenu(msg, character); return;
        }
        if ((m = content.match(/\s--swapfirst\s+([A-Za-z-]+)/))) {
            if ((cs.pendingBoosts || 0) > 0 || (cs.pendingAverageRaises || 0) > 0 ||
                (cs.houseAverageRaisesRemaining || 0) > 0 || (cs.pendingHouseAverageRaises || 0) > 0) {
                whisperPlayer(msg, card('RMU Stat Swaps',
                    `Finish all post-roll boosts first. Normal boosts remaining: <b>${cs.pendingBoosts || 0}</b>; ` +
                    `house-rule average boosts remaining: <b>${cs.houseAverageRaisesRemaining || 0}</b>.`));
                return;
            }
            if ((cs.pendingSwaps || 0) < 1) cs.pendingSwaps = 2;
            const stat = findStat(m[1]);
            if (!stat) { whisperPlayer(msg, card('RMU Stat Swap', 'Unknown stat.')); return; }
            cs.pendingSwapFirst = stat.name;
            swapMenu(msg, character); return;
        }
        if ((m = content.match(/\s--swapsecond\s+([A-Za-z-]+)/))) {
            if ((cs.pendingBoosts || 0) > 0 || (cs.pendingAverageRaises || 0) > 0 ||
                (cs.houseAverageRaisesRemaining || 0) > 0 || (cs.pendingHouseAverageRaises || 0) > 0) {
                whisperPlayer(msg, card('RMU Stat Swaps',
                    `Finish all post-roll boosts first. Normal boosts remaining: <b>${cs.pendingBoosts || 0}</b>; ` +
                    `house-rule average boosts remaining: <b>${cs.houseAverageRaisesRemaining || 0}</b>.`));
                return;
            }
            if (!cs.pendingSwapFirst) { swapMenu(msg, character); return; }
            const first = cs.pendingSwapFirst;
            cs.pendingSwapFirst = null;
            if (swapCreationStats(msg, character, first, m[1])) cs.pendingSwaps = Math.max(0, (cs.pendingSwaps || 1) - 1);
            if (cs.pendingSwaps > 0) swapMenu(msg, character);
            return;
        }
        if (/\s--swapcancel\b/.test(content)) {
            cs.pendingSwapFirst = null;
            swapMenu(msg, character); return;
        }

        const highestName = fixedRaiseTargetName(charId, 90);
        const secondName = fixedRaiseTargetName(charId, 85);
        const highest = highestName ? findStat(highestName) : null;
        const second = secondName ? findStat(secondName) : null;
        const highestVals = highest ? originalCreationRolls(charId, highest.name) : null;
        const secondVals = second ? originalCreationRolls(charId, second.name) : null;

        const body = `<div><b>${html(character.get('name'))}</b></div>` +
            `<div style="margin-top:4px"><b>Important:</b> the official Charactermancer requires two stat-boost choices. Choose any legal options there, but leave both stat swaps as <b>No swap</b>. ` +
            `RMU Tools automatically removes the Charactermancer boost effects before applying the fourth die.</div>` +
            `<div style="margin-top:5px"><b>Workflow</b></div>` +
            `<div>1. Undo mandatory Charactermancer boosts and roll the fourth die</div>` +
            `<div>2. Spend your 2 post-roll boosts</div>` +
            `<div>3. Perform your 2 post-roll swaps at the end</div>` +
            `<div style="margin-top:6px">Normal post-roll boosts remaining: <b>${cs.pendingBoosts || 0}</b></div>` +
            `<div>Extra house-rule Raise-to-Average boosts remaining: <b>${cs.houseAverageRaisesRemaining || 0}</b></div>` +
            `<div>Post-roll swaps remaining: <b>${cs.pendingSwaps || 0}</b></div>` +
            `<div style="margin-top:6px">${button('Prepare: undo Charactermancer boosts', `!rmu-stats --char ${charId} --prepare`)}</div>` +
            `<div style="margin-top:4px">${button('1. Undo boosts + roll fourth die', `!rmu-stats --char ${charId} --extra`)}</div>` +
            `<div style="margin-top:4px">${button('Reset counters/ranking only', `!rmu-stats --char ${charId} --resetworkflow`)}</div>` +
            `<div style="margin-top:6px"><b>Normal RMU boosts (2 choices)</b></div>` +
            `<div>${button('Raise to average', `!rmu-stats --char ${charId} --average 1`)} ` +
            `${button('Two normal average raises', `!rmu-stats --char ${charId} --average 2`)}</div>` +
            `<div style="margin-top:4px">${button('Raise highest temp to 90', `!rmu-stats --char ${charId} --raise90`)}` +
            `${highest ? ` &mdash; ${html(highest.label)} ${highestVals ? highestVals.temp + '/' + highestVals.pot : ''}` : ''}</div>` +
            `<div style="margin-top:4px">${button('Raise second-highest temp to 85', `!rmu-stats --char ${charId} --raise85`)}` +
            `${second ? ` &mdash; ${html(second.label)} ${secondVals ? secondVals.temp + '/' + secondVals.pot : ''}` : ''}</div>` +
            `<div style="margin-top:6px"><b>House rule: 3 extra Raise-to-Average boosts</b></div>` +
            `<div>${button('Use house-rule average boosts', `!rmu-stats --char ${charId} --houseaverage ${cs.houseAverageRaisesRemaining || 3}`)}</div>` +
            `<div style="font-size:90%">At Superior these raise any chosen stat to at least Temp 56 / Pot 78. They are separate from the two normal RMU boost choices.</div>` +
            `<div style="margin-top:6px"><b>Swaps (after all boosts)</b></div>` +
            `<div>${button('Two stat swaps', `!rmu-stats --char ${charId} --swaps 2`)}</div>` +
            `<div style="margin-top:6px;font-size:90%">The 85/90 buttons follow the locked post-roll ranking ` +
            `of your creation stats, so they are not affected by the order in which you click them later.</div>`;
        whisperPlayer(msg, card('RMU Stat House Rules', body));
    }

    function mainMenu(msg) {
        const ext = extractCharArg(msg.content), character = selectedCharacter(msg, ext.charId);
        if (!character) {
            whisperPlayer(msg, card('RMU Tools', 'Select a token representing an RMU character.<br><br>' +
                '<code>!rmu-stats</code> — stat house rules<br><code>!rmu-buff</code> — custom buffs'));
            return;
        }
        const cid = character.id;
        whisperPlayer(msg, card('RMU Tools', `<div><b>${html(character.get('name'))}</b></div>` +
            `<div style="margin-top:5px">${button('Stat house rules', `!rmu-stats --char ${cid}`)}</div>` +
            `<div style="margin-top:4px">${button('Buff manager', `!rmu-buff --char ${cid} --menu`)}</div>`));
    }

    function handleInput(msg) {
        if (msg.type !== 'api') return;
        if (/^!rmu-buff\b/i.test(msg.content)) { handleBuff(msg, msg.content); return; }
        if (/^!rmu-stats\b/i.test(msg.content)) { handleStats(msg, msg.content); return; }
        if (/^!rmu\b/i.test(msg.content)) mainMenu(msg);
    }

    function registerEventHandlers() { on('chat:message', handleInput); }

    return { CheckInstall: checkInstall, RegisterEventHandlers: registerEventHandlers };
}());

on('ready', function () {
    'use strict';
    RMUTools.CheckInstall();
    RMUTools.RegisterEventHandlers();
});
