/*
 * RMU Tools for Roll20
 * Version 0.1.0
 *
 * Designed for the official "Rolemaster Unified by Iron Crown Enterprises"
 * character sheet.
 *
 * Features:
 *   1) Optional post-Charactermancer fourth stat die.
 *   2) Two (configurable) extra "raise to average" stat boosts.
 *   3) Pathfinder-like custom buffs managed from chat.
 *
 * IMPORTANT:
 *   Roll20 Mods cannot execute inside the official Charactermancer sandbox.
 *   The stat adjustment is therefore applied AFTER character creation.
 *
 * Commands:
 *   !rmu
 *   !rmu-stats --extra
 *   !rmu-stats --average 2
 *   !rmu-stats --raise agility
 *
 *   !rmu-buff --menu
 *   !rmu-buff --add Bless|+10 to db, +10 to rr
 *   !rmu-buff --toggle <id>
 *   !rmu-buff --on <id>
 *   !rmu-buff --off <id>
 *   !rmu-buff --del <id>
 *   !rmu-buff --refresh
 *
 * All commands operate on the selected token unless --char <character-id>
 * is supplied. Buttons generated by the Mod include --char automatically.
 */

var RMUTools = RMUTools || (function () {
    'use strict';

    const SCRIPT = 'RMUTools';
    const VERSION = '0.1.0';
    const STATE_VERSION = 1;
    const STATE_KEY = 'RMUTools';
    const BUFF_PREFIX = 'RMU Buff [';

    const STAT_INFO = [
        { name: 'agility',        abbr: 'ag', label: 'Agility' },
        { name: 'constitution',   abbr: 'co', label: 'Constitution' },
        { name: 'empathy',        abbr: 'em', label: 'Empathy' },
        { name: 'intuition',      abbr: 'in', label: 'Intuition' },
        { name: 'memory',         abbr: 'me', label: 'Memory' },
        { name: 'presence',       abbr: 'pr', label: 'Presence' },
        { name: 'quickness',      abbr: 'qu', label: 'Quickness' },
        { name: 'reasoning',      abbr: 're', label: 'Reasoning' },
        { name: 'selfdiscipline', abbr: 'sd', label: 'Self Discipline' },
        { name: 'strength',       abbr: 'st', label: 'Strength' }
    ];

    const STAT_ALIASES = (function () {
        const m = {};
        STAT_INFO.forEach(s => {
            m[s.name] = s.abbr;
            m[s.abbr] = s.abbr;
            m[s.label.toLowerCase().replace(/\s+/g, '')] = s.abbr;
        });
        m['self-discipline'] = 'sd';
        m['self discipline'] = 'sd';
        return m;
    }());

    const RR_ATTRS = {
        arcane:     'rr_arcane_misc',
        channeling: 'rr_channeling_misc',
        essence:    'rr_essence_misc',
        mentalism:  'rr_mentalism_misc',
        physical:   'rr_physical_misc',
        fear:       'rr_fear_misc'
    };

    const POWER_LEVELS = {
        average:   { min: 0,  temp: 51, pot: 76 },
        superior:  { min: 11, temp: 56, pot: 78 },
        heroic:    { min: 21, temp: 61, pot: 81 },
        legendary: { min: 31, temp: 66, pot: 83 },
        epic:      { min: 41, temp: 71, pot: 86 }
    };

    function checkInstall() {
        if (!state[STATE_KEY]) {
            state[STATE_KEY] = { version: STATE_VERSION, characters: {} };
        }
        if (!state[STATE_KEY].characters) state[STATE_KEY].characters = {};
        log(`${SCRIPT} v${VERSION} ready`);
    }

    function charState(charId) {
        const root = state[STATE_KEY];
        if (!root.characters[charId]) {
            root.characters[charId] = {
                buffs: {},
                managedAttrs: [],
                pendingAverageRaises: 0
            };
        }
        return root.characters[charId];
    }

    function html(s) {
        return String(s == null ? '' : s)
            .replace(/&/g, '&amp;').replace(/</g, '&lt;')
            .replace(/>/g, '&gt;').replace(/"/g, '&quot;');
    }

    function whisper(who, body) {
        const target = String(who || 'gm').replace(/"/g, '');
        sendChat(SCRIPT, `/w "${target}" ${body}`, null, { noarchive: true });
    }

    function card(title, body) {
        return `<div style="border:1px solid #777;background:#fff;padding:8px;border-radius:4px;">` +
               `<div style="font-weight:bold;font-size:1.1em;margin-bottom:6px;">${html(title)}</div>` +
               body + `</div>`;
    }

    function button(label, command) { return `[${label}](${command})`; }

    function getAttrObj(charId, name) {
        return findObjs({ _type: 'attribute', _characterid: charId, name: name })[0];
    }

    function getAttr(charId, name, def) {
        const obj = getAttrObj(charId, name);
        if (!obj) return def;
        const v = obj.get('current');
        return (v === undefined || v === null || v === '') ? def : v;
    }

    function setAttr(charId, name, value, worker) {
        let obj = getAttrObj(charId, name);
        if (!obj) {
            obj = createObj('attribute', { characterid: charId, name: name, current: value });
            if (worker && obj && obj.setWithWorker) obj.setWithWorker({ current: value });
            return obj;
        }
        if (worker && obj.setWithWorker) obj.setWithWorker({ current: value });
        else obj.set('current', value);
        return obj;
    }

    function selectedCharacter(msg, explicitId) {
        if (explicitId) {
            const c = getObj('character', explicitId);
            if (c) return c;
        }
        if (msg.selected && msg.selected.length) {
            for (let i = 0; i < msg.selected.length; i++) {
                const token = getObj('graphic', msg.selected[i]._id);
                if (!token) continue;
                const charId = token.get('represents');
                if (!charId) continue;
                const c = getObj('character', charId);
                if (c) return c;
            }
        }
        return null;
    }

    function extractCharArg(content) {
        const m = content.match(/\s--char\s+([A-Za-z0-9_-]+)/);
        if (!m) return { charId: null, content: content };
        return { charId: m[1], content: content.replace(m[0], '') };
    }

    function safeMiscParse(value) {
        if (!value) return [];
        try {
            const parsed = JSON.parse(value);
            return Array.isArray(parsed) ? parsed : [];
        } catch (e) { return []; }
    }

    function miscSetNamedValue(value, name, number) {
        const arr = safeMiscParse(value);
        let found = false;
        arr.forEach(o => {
            if (o && o.name === name) {
                delete o.absolute;
                o.value = parseInt(number, 10) || 0;
                found = true;
            }
        });
        if (!found) arr.push({ name: name, value: parseInt(number, 10) || 0 });
        return JSON.stringify(arr);
    }

    function miscSetAbsolute(value, name, number) {
        const arr = safeMiscParse(value);
        let found = false;
        arr.forEach(o => {
            if (o && o.name === name) {
                delete o.value;
                o.absolute = parseInt(number, 10) || 0;
                found = true;
            }
        });
        if (!found) arr.push({ name: name, absolute: parseInt(number, 10) || 0 });
        return JSON.stringify(arr);
    }

    function miscTotal(value) {
        const arr = safeMiscParse(value);
        let total = 0;
        arr.forEach(o => {
            if (!o) return;
            if (Object.prototype.hasOwnProperty.call(o, 'absolute')) total = parseInt(o.absolute, 10) || 0;
            else if (Object.prototype.hasOwnProperty.call(o, 'value')) total += parseInt(o.value, 10) || 0;
        });
        return total;
    }

    function cleanTargetText(s) {
        return String(s || '').trim().toLowerCase().replace(/\s+/g, ' ');
    }

    function resolveEffectTargets(charId, targetText) {
        let t = cleanTargetText(targetText).replace(/^to\s+/, '');
        if (t === 'db' || t === 'defensive bonus' || t === 'defence' || t === 'defense') return ['db_misc'];
        if (t === 'rr' || t === 'rrs' || t === 'resistance' || t === 'resistance roll' || t === 'resistance rolls') {
            return Object.keys(RR_ATTRS).map(k => RR_ATTRS[k]);
        }

        let rr = t.match(/^(?:rr\s+|resistance(?:\s+roll)?\s+)(arcane|channeling|essence|mentalism|physical|fear)$/);
        if (!rr) rr = t.match(/^(arcane|channeling|essence|mentalism|physical|fear)\s+(?:rr|resistance(?:\s+roll)?)$/);
        if (rr) return [RR_ATTRS[rr[1]]];

        const statKey = t.replace(/\s+/g, '');
        if (STAT_ALIASES[t] || STAT_ALIASES[statKey]) return [(STAT_ALIASES[t] || STAT_ALIASES[statKey]) + '_misc'];

        if (t.indexOf('attr:') === 0) {
            let a = t.substring(5).trim();
            if (a && !/_misc$/.test(a)) a += '_misc';
            return a ? [a] : [];
        }

        const candidate = t.replace(/[^a-z0-9]/g, '') + '_misc';
        if (getAttrObj(charId, candidate)) return [candidate];
        return [];
    }

    function parseEffects(charId, effectText) {
        const clauses = String(effectText || '').split(/[,;\n]+/).map(s => s.trim()).filter(Boolean);
        const effects = [], errors = [];
        clauses.forEach(clause => {
            const m = clause.match(/^([+-]?\d+)\s+(?:to\s+)?(.+)$/i);
            if (!m) { errors.push(`Could not parse "${clause}"`); return; }
            const value = parseInt(m[1], 10);
            const targetText = m[2].trim();
            const attrs = resolveEffectTargets(charId, targetText);
            if (!attrs.length) { errors.push(`Unknown target "${targetText}"`); return; }
            effects.push({ value: value, target: targetText, attrs: attrs });
        });
        return { effects: effects, errors: errors };
    }

    function buffTag(buff) { return `${BUFF_PREFIX}${buff.id}] ${buff.name}`; }

    function reconcileBuffs(charId) {
        const cs = charState(charId), activeByAttr = {};
        Object.keys(cs.buffs).forEach(id => {
            const buff = cs.buffs[id];
            if (!buff.active) return;
            buff.effects.forEach(e => e.attrs.forEach(attr => {
                if (!activeByAttr[attr]) activeByAttr[attr] = [];
                activeByAttr[attr].push({ name: buffTag(buff), value: e.value });
                if (cs.managedAttrs.indexOf(attr) === -1) cs.managedAttrs.push(attr);
            }));
        });

        cs.managedAttrs.forEach(attr => {
            let arr = safeMiscParse(getAttr(charId, attr, '[]'));
            arr = arr.filter(o => !(o && typeof o.name === 'string' && o.name.indexOf(BUFF_PREFIX) === 0));
            (activeByAttr[attr] || []).forEach(e => arr.push({ name: e.name, value: e.value }));
            setAttr(charId, attr, JSON.stringify(arr), true);
        });
    }

    function buffMenu(msg, character) {
        const charId = character.id, cs = charState(charId);
        const buffs = Object.keys(cs.buffs).map(id => cs.buffs[id]);
        let body = `<div><b>${html(character.get('name'))}</b></div>`;
        body += `<div style="margin:5px 0;">` +
                button('Add buff', `!rmu-buff --char ${charId} --add ?{Buff name}|?{Effects|+10 to db, +10 to rr}`) +
                ` ${button('Refresh', `!rmu-buff --char ${charId} --refresh`)}</div>`;
        if (!buffs.length) body += `<div><i>No custom buffs defined.</i></div>`;
        else buffs.forEach(buff => {
            const status = buff.active ? 'ON' : 'off';
            const effects = buff.effects.map(e => `${e.value >= 0 ? '+' : ''}${e.value} to ${e.target}`).join(', ');
            body += `<div style="border-top:1px solid #ddd;padding-top:4px;margin-top:4px;">` +
                    `<b>${html(buff.name)}</b> [${status}]<br><span style="font-size:90%">${html(effects)}</span><br>` +
                    `${button(buff.active ? 'Disable' : 'Enable', `!rmu-buff --char ${charId} --toggle ${buff.id}`)} ` +
                    `${button('Delete', `!rmu-buff --char ${charId} --del ${buff.id}`)}</div>`;
        });
        body += `<div style="margin-top:6px;font-size:90%">Effect syntax: <code>+10 to db</code>, ` +
                `<code>+10 to rr</code>, <code>+20 to fear rr</code>, or ` +
                `<code>+10 to attr:perception_misc</code>.</div>`;
        whisper(msg.who, card('RMU Buffs', body));
    }

    function handleBuff(msg, raw) {
        const ext = extractCharArg(raw), character = selectedCharacter(msg, ext.charId);
        if (!character) { whisper(msg.who, card('RMU Buffs', 'Select a token representing a character, then try again.')); return; }
        const charId = character.id, cs = charState(charId), content = ext.content;
        let m;

        if ((m = content.match(/\s--add\s+([\s\S]+)$/))) {
            const spec = m[1], split = spec.indexOf('|');
            if (split < 1) { whisper(msg.who, card('RMU Buffs', 'Use <code>--add Name|+10 to db, +10 to rr</code>.')); return; }
            const name = spec.substring(0, split).trim(), effectText = spec.substring(split + 1).trim();
            const parsed = parseEffects(charId, effectText);
            if (!name || !parsed.effects.length || parsed.errors.length) {
                let body = !name ? 'Buff name is missing.<br>' : '';
                parsed.errors.forEach(e => body += `${html(e)}<br>`);
                whisper(msg.who, card('RMU Buffs', body || 'No valid effects.')); return;
            }
            const id = Date.now().toString(36) + randomInteger(9999).toString(36);
            cs.buffs[id] = { id: id, name: name, effectText: effectText, effects: parsed.effects, active: true };
            reconcileBuffs(charId); buffMenu(msg, character); return;
        }

        const actionMatch = content.match(/\s--(toggle|on|off|del)\s+([A-Za-z0-9_-]+)/);
        if (actionMatch) {
            const action = actionMatch[1], id = actionMatch[2], buff = cs.buffs[id];
            if (!buff) { whisper(msg.who, card('RMU Buffs', 'Buff not found.')); return; }
            if (action === 'toggle') buff.active = !buff.active;
            if (action === 'on') buff.active = true;
            if (action === 'off') buff.active = false;
            if (action === 'del') delete cs.buffs[id];
            reconcileBuffs(charId); buffMenu(msg, character); return;
        }

        if (/\s--refresh\b/.test(content)) { reconcileBuffs(charId); buffMenu(msg, character); return; }
        buffMenu(msg, character);
    }

    function powerLevelInfo(charId) {
        const raw = String(getAttr(charId, 'powerlevel', 'Superior')).trim().toLowerCase();
        return POWER_LEVELS[raw] || POWER_LEVELS.superior;
    }

    function rerollD100Below(minimum) {
        let r;
        do { r = randomInteger(100); } while (minimum > 0 && r < minimum);
        return r;
    }

    function originalCreationRolls(charId, statName) {
        const arr = safeMiscParse(getAttr(charId, statName + '_misc', ''));
        for (let i = 0; i < arr.length; i++) {
            const o = arr[i];
            if (!o || typeof o.name !== 'string') continue;
            const m = o.name.match(/^Temp\s+(\d+),\s*Pot\s+(\d+)/i);
            if (m) return { temp: parseInt(m[1], 10), pot: parseInt(m[2], 10), index: i, array: arr };
        }
        return null;
    }

    function applyExtraStatDie(msg, character) {
        const charId = character.id, pli = powerLevelInfo(charId), results = [], updates = [];
        STAT_INFO.forEach(stat => {
            const original = originalCreationRolls(charId, stat.name);
            if (!original) { results.push(`${stat.label}: could not find original creation roll`); return; }
            const extra = rerollD100Below(pli.min);
            const sorted = [original.pot, original.temp, extra].sort((a, b) => b - a);
            const newPot = sorted[0], newTemp = sorted[1];

            const entry = original.array[original.index];
            entry.name = `Temp ${newTemp}, Pot ${newPot} (4th die ${extra})`;
            entry.absolute = newTemp;
            delete entry.value;
            setAttr(charId, stat.name + '_misc', JSON.stringify(original.array), true);

            const potAttr = stat.name + '_pot_misc';
            const currentPot = miscTotal(getAttr(charId, potAttr, '[]'));
            if (newPot > currentPot) {
                setAttr(charId, potAttr, miscSetNamedValue(getAttr(charId, potAttr, '[]'), 'Creation', newPot), true);
            }

            const changed = (newPot !== original.pot || newTemp !== original.temp);
            results.push(`${stat.label}: rolled <b>${extra}</b> &rarr; ${original.pot}/${original.temp} becomes ` +
                         `<b>${newPot}/${newTemp}</b>${changed ? '' : ' (no change)'}`);
            updates.push({ stat: stat.name, die: extra, changed: changed });
        });

        charState(charId).lastExtraDie = { when: Date.now(), powerMin: pli.min, results: updates };
        whisper(msg.who, card('RMU fourth stat die',
            `<div><b>${html(character.get('name'))}</b></div><div style="margin-top:5px">${results.join('<br>')}</div>` +
            `<div style="margin-top:6px;font-size:90%">This is a post-Charactermancer adjustment. ` +
            `It keeps any later absolute stat boosts already recorded by the official sheet.</div>`));
    }

    function currentStatValue(charId, statName) { return miscTotal(getAttr(charId, statName + '_misc', '[]')); }
    function currentPotValue(charId, statName) { return miscTotal(getAttr(charId, statName + '_pot_misc', '[]')); }

    function averageRaiseMenu(msg, character) {
        const charId = character.id, cs = charState(charId), pli = powerLevelInfo(charId);
        const remaining = cs.pendingAverageRaises || 0;
        let body = `<div><b>${html(character.get('name'))}</b></div>` +
                   `<div>Raises remaining: <b>${remaining}</b></div>` +
                   `<div>Average: Temp ${pli.temp}, Pot ${pli.pot}</div>`;
        if (remaining > 0) {
            body += `<div style="margin-top:5px">Choose a stat:</div>`;
            STAT_INFO.forEach(stat => {
                const temp = currentStatValue(charId, stat.name), pot = currentPotValue(charId, stat.name);
                body += `<div>${button(stat.label, `!rmu-stats --char ${charId} --raise ${stat.name}`)} ${temp}/${pot}</div>`;
            });
        } else body += `<div style="margin-top:5px"><i>No extra average raises pending.</i></div>`;
        whisper(msg.who, card('RMU raise to average', body));
    }

    function applyAverageRaise(msg, character, statName) {
        const charId = character.id, cs = charState(charId);
        if ((cs.pendingAverageRaises || 0) < 1) {
            whisper(msg.who, card('RMU Stats', 'No extra average raises are pending. Use <code>!rmu-stats --average 2</code> first.'));
            return;
        }
        const stat = STAT_INFO.filter(s => s.name === statName.toLowerCase())[0];
        if (!stat) { whisper(msg.who, card('RMU Stats', `Unknown stat "${html(statName)}".`)); return; }

        const pli = powerLevelInfo(charId), tempAttr = stat.name + '_misc', potAttr = stat.name + '_pot_misc';
        const oldTemp = currentStatValue(charId, stat.name), oldPot = currentPotValue(charId, stat.name);
        const newTemp = Math.max(oldTemp, pli.temp), newPot = Math.max(oldPot, pli.pot);

        setAttr(charId, tempAttr, miscSetAbsolute(getAttr(charId, tempAttr, '[]'), 'RMU Mod: Raise to average', newTemp), true);
        setAttr(charId, potAttr, miscSetAbsolute(getAttr(charId, potAttr, '[]'), 'RMU Mod: Raise to average', newPot), true);
        cs.pendingAverageRaises -= 1;

        whisper(msg.who, card('RMU Stats', `${html(stat.label)} raised from ${oldTemp}/${oldPot} to ` +
            `<b>${newTemp}/${newPot}</b>. ${cs.pendingAverageRaises} extra raise(s) remaining.`));
        if (cs.pendingAverageRaises > 0) averageRaiseMenu(msg, character);
    }

    function handleStats(msg, raw) {
        const ext = extractCharArg(raw), character = selectedCharacter(msg, ext.charId);
        if (!character) { whisper(msg.who, card('RMU Stats', 'Select a token representing a character, then try again.')); return; }
        const charId = character.id, content = ext.content;
        let m;
        if (/\s--extra\b/.test(content)) { applyExtraStatDie(msg, character); return; }
        if ((m = content.match(/\s--average(?:\s+(\d+))?/))) {
            charState(charId).pendingAverageRaises = Math.max(1, Math.min(10, parseInt(m[1] || '2', 10)));
            averageRaiseMenu(msg, character); return;
        }
        if ((m = content.match(/\s--raise\s+([A-Za-z-]+)/))) { applyAverageRaise(msg, character, m[1]); return; }

        const body = `<div><b>${html(character.get('name'))}</b></div>` +
            `<div style="margin-top:5px">${button('Roll fourth die', `!rmu-stats --char ${charId} --extra`)}</div>` +
            `<div style="margin-top:4px">${button('Two extra raises to average', `!rmu-stats --char ${charId} --average 2`)}</div>` +
            `<div style="margin-top:6px;font-size:90%">Run these after the official Charactermancer has finished character creation.</div>`;
        whisper(msg.who, card('RMU Stat House Rules', body));
    }

    function mainMenu(msg) {
        const ext = extractCharArg(msg.content), character = selectedCharacter(msg, ext.charId);
        if (!character) {
            whisper(msg.who, card('RMU Tools', 'Select a token representing an RMU character.<br><br>' +
                '<code>!rmu-stats</code> — stat house rules<br><code>!rmu-buff</code> — custom buffs'));
            return;
        }
        const cid = character.id;
        whisper(msg.who, card('RMU Tools', `<div><b>${html(character.get('name'))}</b></div>` +
            `<div style="margin-top:5px">${button('Stat house rules', `!rmu-stats --char ${cid}`)}</div>` +
            `<div style="margin-top:4px">${button('Buff manager', `!rmu-buff --char ${cid} --menu`)}</div>`));
    }

    function handleInput(msg) {
        if (msg.type !== 'api') return;
        if (/^!rmu-buff\b/i.test(msg.content)) { handleBuff(msg, msg.content); return; }
        if (/^!rmu-stats\b/i.test(msg.content)) { handleStats(msg, msg.content); return; }
        if (/^!rmu\b/i.test(msg.content)) mainMenu(msg);
    }

    function registerEventHandlers() { on('chat:message', handleInput); }

    return { CheckInstall: checkInstall, RegisterEventHandlers: registerEventHandlers };
}());

on('ready', function () {
    'use strict';
    RMUTools.CheckInstall();
    RMUTools.RegisterEventHandlers();
});
